### ISSUE TITLE
first a1 test results

### ISSUE THREAD

**Issue by martin-frbg** [castle-engine/castle-model-viewer-mobile#1]
Looking good so far on older Sony zx1 compact , thanks for making this available.
Few minor oddities I noticed:
- switching a scene that starts in Examine mode to either Walk or Fly makes the object fly off to some very distant place in the top left corner of the universe, no chance to bring it back
- no support for DEF BackgroundColor in VRML1 (supported in regular view3dscene)
- headlight seems kind of weak ?
- "teapot fresnel and toon shader" demo scene generates a bunch of "PLUG declaration unexpected character b" warnings that appear to be from test code that looks like it is not commented out as intended

(apologies if you do not actually want to see issues here just yet)

**Comment by michaliskambi** [comment]
Thank you for reporting -- I didn't expect reports so soon, but I appreciate them! :)

I'll test them ASAP.

This version of view3dscene-mobile was build with the same very latest CGE, so it should support the same X3D/rendering features as latest view3dscene (from snapshots http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ ). There are some bits missing in OpenGLES, but not much.

Can you clarify these two issues:

> no support for DEF BackgroundColor in VRML1 (supported in regular view3dscene)

What do you mean here? `Background`, `TextureBackground`  and `ImageBackground` nodes should be supported, like in regular view3dscene.

> headlight seems kind of weak ?

It should be look the same as in regular view3dscene.

**Comment by martin-frbg** [comment]
Sorry, my fault - the DEF BackgroundColor was actually ignored by the desktop version as well (and probably rightly so - these are some very old vrml1 files I was looking at, the DEF trick may have been a non-standard feature of some equally ancient viewer). Could be that desktop 3.18.0 simply defaults to a light background on VRML1 while the android version defaults to black ? 
And I am happy to confirm that VRML2 Background is supported very nicely. :)

**Comment by michaliskambi** [comment]
> switching a scene that starts in Examine mode to either Walk or Fly makes the object fly off to some very distant place in the top left corner of the universe, no chance to bring it back

Fixed. That was a deliberate, but admittedly confusing, change to CGE recently -- "Walk" was turning "on" gravity, and you were falling down infinitely.

I reimplemented (but better) the old behavior to prevent falling down when you're outside of the bounding box of the scene.

> teapot fresnel and toon shader" demo scene generates a bunch of "PLUG declaration unexpected character b" warnings

Fixed. This file contained an old test that some invalid PLUG_xxx strings are ignored (they can be ignored since they are in GLSL comments). Accidentally, they were still ignored but caused visible warning.

For completely unrelated reason, loading this scene also set wrong initial camera. Fixed too.

> Could be that desktop 3.18.0 simply defaults to a light background on VRML1 while the android version defaults to black ?

They both default to dark-but-not-exactly-black now. (Comparing latest view3dscene-mobile, with view3dcene from http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ ). Stable view3dscene 3.18.0 defaulted to pure black background.

I made some other fixes :) I'll upload new release soon. Thank you for the report, please keep testing!

**Comment by martin-frbg** [comment]
Thanks for the fixes, working great now.

> They both default to dark-but-not-exactly-black now. (Comparing latest view3dscene-mobile, with view3dcene from http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ ). Stable view3dscene 3.18.0 defaulted to pure black background.

The desktop version has an option to set a user-defined color in the Preferences, perhaps
 this could be useful in the mobile one as well ? (And yes, it may well have been me/us pestering you about this setting way back when... :smile: )

**Comment by michaliskambi** [comment]
> The desktop version has an option to set a user-defined color in the Preferences, perhaps
this could be useful in the mobile one as well ?

Makes sense. I added this to my TODO -- I'll see when I implement it (it's easy, but I don't want to overcrowd the settings on mobile, so I'd like to present it in nice concise UI).
